spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:32843/railway
spring.datasource.username=root
spring.datasource.password=mpYtrqOkgcayftnxayStXESPRPxYCnSs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}